# -- coding: utf-8 --
"""OCRv5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YQKYf0977yAYhfwwxEZNxHVr_Z7ULTV
"""

# !pip install opencv-python pytesseract easyocr pandas pillow numpy

"""
Router Label OCR Information Extraction - Standalone Script
Extracts WiFi passwords, IP addresses, and credentials from router label images
"""

import cv2
import numpy as np
import os
from PIL import Image
import pytesseract
import easyocr
import re
import pandas as pd
import argparse
import sys
import warnings
warnings.filterwarnings('ignore')


class RouterInfoExtractor:
    def __init__(self):
        print("🤖 Initializing OCR engines...")
        
        # Initialize EasyOCR
        self.easyocr_reader = easyocr.Reader(['en'], gpu=False)
        
        # Check if Tesseract is available
        self.tesseract_available = False
        try:
            pytesseract.get_tesseract_version()
            self.tesseract_available = True
            print("✅ Tesseract OCR: Available")
        except:
            print("⚠  Tesseract OCR: Not available (will use EasyOCR only)")
            print("   Install Tesseract for better OCR results: https://github.com/tesseract-ocr/tesseract")
        
        print("✅ EasyOCR: Available")

        # Define patterns for common router information
        self.patterns = {
            'wpa_key': [
                r'WPA\s*Key\s*:?\s*([A-Za-z0-9]+)',
                r'Key\s*:?\s*([A-Za-z0-9]{8,})',
                r'WPA\s*:?\s*([A-Za-z0-9]{8,})',
            ],
            'ip_address': [
                r'IP\s*Address\s*:?\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})',
                r'IP\s*:?\s*(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})',
                r'(192\.168\.\d{1,3}\.\d{1,3})',
                r'(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})',
            ],
            'ssid': [
                r'SSID\s*:?\s*([A-Za-z0-9_-]+)',
                r'Network\s*Name\s*:?\s*([A-Za-z0-9_-]+)',
                r'WiFi\s*Name\s*:?\s*([A-Za-z0-9_-]+)',
            ],
            'mac_address': [
                r'MAC\s*:?\s*([A-Fa-f0-9]{2}[:-]?[A-Fa-f0-9]{2}[:-]?[A-Fa-f0-9]{2}[:-]?[A-Fa-f0-9]{2}[:-]?[A-Fa-f0-9]{2}[:-]?[A-Fa-f0-9]{2})',
                r'([A-Fa-f0-9]{12})',
                r'MTA\s*MAC\s*:?\s*([A-Fa-f0-9]+)',
            ],
            'model_number': [
                r'Model\s*:?\s*([A-Za-z0-9-_]+)',
                r'Model\s*No\s*:?\s*([A-Za-z0-9-_]+)',
                r'GigaSpire\s*BLAST\s*Model\s*:?\s*([A-Za-z0-9-_]+)',
            ],
            'serial_number': [
                r'Serial\s*No\s*:?\s*([A-Za-z0-9]+)',
                r'S/N\s*:?\s*([A-Za-z0-9]+)',
                r'Serial\s*:?\s*([A-Za-z0-9]+)',
            ]
        }
        print("✅ RouterInfoExtractor initialized successfully!")

    def preprocess_image(self, image):
        """Preprocess image for better OCR results"""
        # Convert to grayscale if needed
        if len(image.shape) == 3:
            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        else:
            gray = image.copy()

        # Apply different preprocessing techniques
        processed_images = {}

        # Original grayscale
        processed_images['original'] = gray

        # Gaussian blur + threshold
        blurred = cv2.GaussianBlur(gray, (5, 5), 0)
        _, thresh1 = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
        processed_images['otsu'] = thresh1

        # Adaptive threshold
        adaptive_thresh = cv2.adaptiveThreshold(
            gray, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2
        )
        processed_images['adaptive'] = adaptive_thresh

        # Morphological operations
        kernel = np.ones((2, 2), np.uint8)
        morph = cv2.morphologyEx(thresh1, cv2.MORPH_CLOSE, kernel)
        processed_images['morphological'] = morph

        # Contrast enhancement
        clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
        enhanced = clahe.apply(gray)
        processed_images['enhanced'] = enhanced

        return processed_images

    def extract_text_tesseract(self, image, config='--psm 6'):
        """Extract text using Tesseract OCR"""
        try:
            text = pytesseract.image_to_string(image, config=config)
            return text.strip()
        except Exception as e:
            print(f"Tesseract error: {e}")
            return ""

    def extract_text_easyocr(self, image):
        """Extract text using EasyOCR"""
        try:
            results = self.easyocr_reader.readtext(image, detail=0)
            return ' '.join(results)
        except Exception as e:
            print(f"EasyOCR error: {e}")
            return ""

    def extract_username_password(self, text):
        """
        Robust extraction for side-by-side username/password formats.
        Handles examples like:
        - User: admin Password: xyz123
        - User admin Password xyz123
        - User/Password: admin/xyz123
        - User/Password; 4dmin/07b61347,
        - login credentials -> foo/bar
        Returns (username, password) or (None, None)
        """
        username = None
        password = None

        # A permissive token for usernames/passwords (adjust min/max length if needed)
        token = r'[A-Za-z0-9._-]{2,64}'

        patterns = [
            # Strict labelled "User ... Password ..." (labels separated by arbitrary whitespace/punctuation)
            rf'(?i)\buser(?:name)?\s*[:;\-–—]?\s*({token})\s*(?:[,;|\-–—\s]{{1,6}})\s*pass(?:word)?\s*[:;\-–—]?\s*({token})\b',
            # Side-by-side with slash or colon: "User/Password: admin/xyz123" or "User/Password; admin/xyz123"
            rf'(?i)\buser\s*/\s*password\s*[:;]?\s*({token})\s*/\s*({token})\b',
            # Label followed by values after punctuation: "User/Password; 4dmin/07b61347"
            rf'(?i)\buser\s*/\s*password\s*[:;]?\s*({token})\s*/\s*({token})',
            # Fallback: "Username: foo, Password: bar" allowing other chars and punctuation around values
            rf'(?i)\busername?\s*[:;]?\s*({token})\D{{0,8}}?password?\s*[:;]?\s*({token})',
            # General fallback: any token/token pair with common separators (careful: may produce false positives)
            rf'(?m)\b({token})\s*[\/:]\s*({token})\b',
        ]

        # Helpers to avoid common false-positives
        def is_ip(s):
            return re.fullmatch(r'\d{1,3}(?:\.\d{1,3}){3}', s) is not None

        def is_mac(s):
            return re.fullmatch(r'(?:[A-Fa-f0-9]{2}[:\-]?){5}[A-Fa-f0-9]{2}', s) is not None or re.fullmatch(r'[A-Fa-f0-9]{12}', s) is not None

        # Clean trailing punctuation often introduced by OCR
        def clean_token(t):
            if t is None:
                return None
            return t.strip(" \t\n\r:;,.\"'`[]()<>")

        for pat in patterns:
            m = re.search(pat, text, re.IGNORECASE)
            if not m:
                continue
            u = clean_token(m.group(1))
            p = clean_token(m.group(2))

            # sanity checks
            if not u or not p:
                continue
            if is_ip(u) or is_ip(p) or is_mac(u) or is_mac(p):
                # skip matches that look like IPs/MACs
                continue

            username, password = u, p
            return username, password

        return None, None

    def extract_information(self, text):
        """Extract specific information using regex patterns"""
        extracted_info = {}

        # Clean up text - normalize whitespace but preserve structure
        text = re.sub(r'\s+', ' ', text)

        # First, try to extract username and password together
        username, password = self.extract_username_password(text)
        extracted_info['username'] = username
        extracted_info['password'] = password

        # Now extract other fields with standard patterns
        for info_type, patterns in self.patterns.items():
            if info_type not in extracted_info:
                extracted_info[info_type] = None

            for pattern in patterns:
                match = re.search(pattern, text, re.IGNORECASE)
                if match:
                    extracted_info[info_type] = match.group(1)
                    break

        return extracted_info

    def process_image(self, image_path, verbose=True):
        """Main processing function"""
        # Load image
        image = cv2.imread(image_path)
        if image is None:
            print(f"❌ Could not load image: {image_path}")
            return None

        if verbose:
            print(f"📸 Processing image: {os.path.basename(image_path)}")
            print(f"📐 Image shape: {image.shape}")

        # Preprocess image
        processed_images = self.preprocess_image(image)

        results = {}

        # Try different OCR methods and preprocessing combinations
        ocr_methods = ['tesseract', 'easyocr']

        for method in ocr_methods:
            results[method] = {}

            for preprocess_name, proc_image in processed_images.items():
                if verbose:
                    print(f"🔍 {method.upper()} with {preprocess_name} preprocessing...")

                # if method == 'tesseract':
                #     # Try different PSM modes for Tesseract
                #     psm_modes = ['--psm 6', '--psm 4', '--psm 11']
                #     best_text = ""

                #     for psm in psm_modes:
                #         text = self.extract_text_tesseract(proc_image, psm)
                #         if len(text) > len(best_text):
                #             best_text = text

                #     extracted_info = self.extract_information(best_text)

                # elif method == 'easyocr':
                if(method == 'easyocr' and (preprocess_name == "original" or preprocess_name == "enhanced")) : 
                    text = self.extract_text_easyocr(proc_image)
                    best_text = text
                    extracted_info = self.extract_information(text)

                results[method][preprocess_name] = {
                        'text': best_text,
                        'extracted_info': extracted_info
                }

                print("########################################################")
                print(best_text)
                print("########################################################")


        return results

    def combine_results(self, results):
        """Combine results from different methods to get best extraction"""
        final_info = {}

        # Initialize with empty values
        all_fields = list(self.patterns.keys()) + ['username', 'password']
        for info_type in all_fields:
            final_info[info_type] = None

        # Priority: EasyOCR > Tesseract, Enhanced/OTSU > Others
        priority_order = [
            ('easyocr', 'enhanced'),
            ('easyocr', 'otsu'),
            ('easyocr', 'original'),
            ('tesseract', 'enhanced'),
            ('tesseract', 'otsu'),
            ('tesseract', 'original'),
        ]

        for info_type in final_info.keys():
            for method, preprocess in priority_order:
                try:
                    if method in results and preprocess in results[method]:
                        value = results[method][preprocess]['extracted_info'].get(info_type)
                        if value and not final_info[info_type]:
                            final_info[info_type] = value
                            break
                except:
                    continue

        return final_info


def process_single_image(image_path, output_format='dict'):
    """
    Process a single router image and extract information

    Args:
        image_path: Path to the image file
        output_format: 'dict' or 'print'

    Returns:
        Dictionary with extracted information
    """
    print("$$$$$$$$$####################",image_path)
    extractor = RouterInfoExtractor()
    results = extractor.process_image(image_path, verbose=True)

    if not results:
        print("❌ Failed to process image")
        return None

    final_info = extractor.combine_results(results)

    if output_format == 'print':
        print("\n" + "="*50)
        print("📊 EXTRACTED INFORMATION")
        print("="*50)
        for key, value in final_info.items():
            icon = "✅" if value else "❌"
            display_name = key.replace('_', ' ').title()
            print(f"{icon} {display_name}: {value if value else 'Not found'}")
        print("="*50)

    return final_info


def process_batch_images(image_folder, image_prefix='router', image_extension='.jpeg',
                        start_num=1, end_num=20, output_csv='extracted_results.csv'):
    """
    Process multiple router images in batch

    Args:
        image_folder: Folder containing images
        image_prefix: Prefix of image files (e.g., 'router')
        image_extension: File extension (e.g., '.jpeg', '.jpg', '.png')
        start_num: Starting number
        end_num: Ending number
        output_csv: Output CSV filename

    Returns:
        Dictionary with all results and saves CSV file
    """
    extractor = RouterInfoExtractor()
    all_results = {}
    processed_count = 0

    print(f"\n📦 BATCH PROCESSING")
    print(f"📁 Folder: {image_folder}")
    print(f"📄 Files: {image_prefix}{start_num}{image_extension} to {image_prefix}{end_num}{image_extension}")
    print("="*60)

    for i in range(start_num, end_num + 1):
        filename = f"{image_prefix}{i}{image_extension}"
        full_path = os.path.join(image_folder, filename)

        if not os.path.exists(full_path):
            print(f"⚠  File not found: {filename}")
            continue

        print(f"\n{'='*60}")
        print(f"Processing: {filename} ({processed_count + 1})")
        print('='*60)

        try:
            results = extractor.process_image(full_path, verbose=False)

            if results:
                final_info = extractor.combine_results(results)
                all_results[filename] = final_info
                processed_count += 1

                # Print summary
                print("📊 Extracted:")
                for key, value in final_info.items():
                    if value:
                        print(f"  ✅ {key.replace('_', ' ').title()}: {value}")
            else:
                print(f"❌ Failed to process {filename}")

        except Exception as e:
            print(f"❌ Error processing {filename}: {str(e)}")
            all_results[filename] = {'error': str(e)}

    print(f"\n🎯 PROCESSING SUMMARY:")
    print(f"Total files processed: {processed_count}")
    print(f"Total files attempted: {end_num - start_num + 1}")

    # Save to CSV
    if all_results:
        df_data = []
        for image_name, info in all_results.items():
            row = {'image_name': image_name}
            row.update(info)
            df_data.append(row)

        df = pd.DataFrame(df_data)
        df.to_csv(output_csv, index=False)
        print(f"\n💾 Results saved to: {output_csv}")
        print(f"\n📊 Sample results:")
        print(df.head())

    return all_results


def extract_specific_field(image_path, field_name='wpa_key'):
    """
    Extract only a specific field from router image

    Args:
        image_path: Path to image
        field_name: Field to extract ('wpa_key', 'username', 'password', 'ip_address', etc.)

    Returns:
        Extracted field value or None
    """
    extractor = RouterInfoExtractor()
    results = extractor.process_image(image_path, verbose=False)

    if not results:
        return None

    final_info = extractor.combine_results(results)
    return final_info.get(field_name)

print("🚀 Router OCR Information Extractor")
print("="*60)

# Example 1: Process single image
# print("\n📋 Example 1: Process Single Image")
# print("-"*60)
# image_path = "OCRouter/router1.jpg"  # Change this to your image path
# if os.path.exists(image_path):
#     info = process_single_image(image_path, output_format='print')
# else:
#     print(f"⚠  Image not found: {image_path}")
#     print("Please update the image_path variable with your actual image file")


# print("\n" + "="*60)
# print("✅ Script completed!")